name: firestore_model
description: Reference counted, realtime Firestore model. Firestore reference & collection builders.
version: 0.0.3
homepage: github.com/volskaya/firestore_model
publish_to: none

environment:
  sdk: ">=2.18.0-44.0.dev <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.11.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^3.1.6
  collection: ^1.15.0
  fast_immutable_collections: ^5.1.2
  firebase_database: ^7.1.2
  flutter_hooks: ^0.18.0
  flutter_mobx: ^2.0.0
  json_annotation: ^4.5.0
  mobx_codegen: ^2.0.1+3
  mobx: ^2.0.1
  provider: ^5.0.0
  riverpod: ^1.0.0-dev.7
  freezed_annotation: ^2.0.3
  flutter_riverpod: ^1.0.0-dev.7
  isolate_handler: ^1.0.0
  quiver: ^3.0.1

  log:
    path: /Users/muru/Projects/packages/flutter_helpers/log
  refresh_storage:
    path: /Users/muru/Projects/packages/flutter_helpers/refresh_storage
  fancy_switcher:
    path: /Users/muru/Projects/packages/fancy_switcher
  delayed_progress_indicator:
    path: /Users/muru/Projects/packages/flutter_helpers/delayed_progress_indicator
  loader_coordinator:
    path: /Users/muru/Projects/packages/flutter_helpers/loader_coordinator
  await_route:
    path: /Users/muru/Projects/packages/flutter_helpers/await_route
  utils:
    path: /Users/muru/Projects/packages/flutter_helpers/utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable: ^6.2.0
  mocktail: ^0.1.4
  freezed: ^2.0.3+1

dependency_overrides:
  mobx:
    path: /Users/muru/Projects/forks/mobx.dart/mobx
  flutter_mobx:
    path: /Users/muru/Projects/forks/mobx.dart/flutter_mobx
  mobx_codegen:
    path: /Users/muru/Projects/forks/mobx.dart/mobx_codegen

flutter:
