name: firestore_model
description: Reference counted, realtime Firestore model. Firestore reference & collection builders.
version: 0.0.2
author: Roland Volskaya
homepage: github.com/volskaya/firestore_model
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^2.2.0
  firebase_database: ^6.1.0
  mobx: 2.0.1
  flutter_mobx: 2.0.0
  mobx_codegen: 2.0.1+3
  json_annotation: ^4.0.1
  provider: ^5.0.0
  flutter_hooks: ^0.17.0
  collection: ^1.15.0
  fast_immutable_collections: ^4.0.6

  log:
    path: /home/projects/packages/flutter_helpers/log
  refresh_storage:
    path: /home/projects/packages/flutter_helpers/refresh_storage
  fancy_switcher:
    path: /home/projects/packages/fancy_switcher
  delayed_progress_indicator:
    path: /home/projects/packages/flutter_helpers/delayed_progress_indicator
  loader_coordinator:
    path: /home/projects/packages/flutter_helpers/loader_coordinator
  await_route:
    path: /home/projects/packages/flutter_helpers/await_route

dependency_overrides:
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

dev_dependencies:
  build_runner:
  json_serializable:

flutter:
