name: firestore_model
description: Reference counted, realtime Firestore model. Firestore reference & collection builders.
version: 0.0.3
homepage: github.com/volskaya/firestore_model
publish_to: none

environment:
  sdk: ">=2.14.0-342.0.dev <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.2.0
  cloud_firestore: ^2.4.0
  collection: ^1.15.0
  fast_immutable_collections: ^5.1.2
  firebase_database: ^7.1.2
  flutter_hooks: ^0.18.0
  flutter_mobx: ^2.0.0
  json_annotation: ^4.1.0
  mobx_codegen: ^2.0.1+3
  mobx: ^2.0.1
  provider: ^5.0.0
  riverpod: ^1.0.0-dev.7
  freezed_annotation: ^0.14.1
  flutter_riverpod: ^1.0.0-dev.7
  isolate_handler: ^1.0.0

  log:
    path: /home/projects/packages/flutter_helpers/log
  refresh_storage:
    path: /home/projects/packages/flutter_helpers/refresh_storage
  fancy_switcher:
    path: /home/projects/packages/fancy_switcher
  delayed_progress_indicator:
    path: /home/projects/packages/flutter_helpers/delayed_progress_indicator
  loader_coordinator:
    path: /home/projects/packages/flutter_helpers/loader_coordinator
  await_route:
    path: /home/projects/packages/flutter_helpers/await_route
  utils:
    path: /home/projects/packages/flutter_helpers/utils

dev_dependencies:
  build_runner:
  json_serializable: ^5.0.0
  mocktail: ^0.1.4
  freezed: ^0.14.1+1

dependency_overrides:
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed
  mobx:
    path: /home/projects/forks/mobx.dart/mobx
  flutter_mobx:
    path: /home/projects/forks/mobx.dart/flutter_mobx
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

flutter:
