name: firestore_model
description: Reference counted, realtime Firestore model. Firestore reference & collection builders.
version: 0.0.2
author: Roland Volskaya
homepage: github.com/volskaya/firestore_model

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.0
  firebase_database: ^4.1.1
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  mobx_codegen:
  json_annotation: ^3.0.1
  provider: ^4.3.2+2
  flutter_hooks: ^0.15.0

  refresh_storage:
    path: /home/projects/packages/flutter_helpers/refresh_storage
  fancy_switcher:
    path: /home/projects/packages/fancy_switcher
  delayed_progress_indicator:
    path: /home/projects/packages/flutter_helpers/delayed_progress_indicator

dependency_overrides:
  analyzer: '0.39.14'

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:

flutter:
